<?php include ('header.php') ?>

<h1 style="text-align:center; text-shadow: 1px 1px red;">Matematika</h1>
<p>A matematika, tárgyát és módszereit tekintve, sajátos tudomány, mely részben a többi tudomány által vizsgált, részben pedig a matematika „belső” fejlődéséből adódóan létrejött (felfedezett, ill. feltalált) rendszereket, struktúrákat, azok absztrakt, közösen meglévő tulajdonságait vizsgálja.</p>
<p>Régebben a „mennyiség és a tér tudományaként” (vagyis a számok és geometriai alakzatok tanaként) határozták meg, a múlt század elejétől kezdve pedig a matematikáról azt tartották, hogy az „a halmazelmélet absztrakt struktúráinak formális logikai szemlélettel és a javarészt erre épülő matematikai jelölésrendszerrel való vizsgálata”.</p>
<p>Ma már nemcsak az első, hanem a második álláspontot is vitathatónak, túlhaladottnak tartják mind egyes tudományfilozófiai, mind egyes didaktikai áramlatok képviselői. A matematikát nehéz pontosan meghatározni, mibenlétének kérdése még manapság is, sőt manapság különösen, vita tárgya, élő és nem lezárt tudományos probléma, mellyel a matematikafilozófia (a filozófia egyik területe, sőt már-már önálló tudományága) foglalkozik. Amíg a matematikába sorolt tevékenységekről, módszerekről és fogalmakról (vagyis mi az, ami a matematika körébe tartozik, és mi az, ami nem) ha nem is teljes, de nagy fokú és vitákat alig-alig kiváltó egyetértés alakult ki, addig a matematika által tanulmányozott fogalmak lételméleti helyzetéről, ismeretelméleti megközelítéséről, magának a matematikának mint tevékenységnek a jellegéről, sőt céljáról („keményvonalas” természet- vagy pedig „szoft” társadalomtudomány, esetleg művészet; empirikus vagy inkább normatív, stb.) a legkülönfélébb releváns elképzelések léteznek egymással párhuzamosan.</p>
<p>Ezért a következőkben megpróbáljuk ehelyett néhány fontos, megkülönböztető sajátosságát kiemelni, melyek egyike-másika más tudományokban is megtalálható, de így együtt az összes csak a matematikában. A matematika sajátossága elsősorban különleges témaválasztásában, kutatási területeiben és módszereiben, nyelv- és jelölésrendszerében rejlik.</p>
<p><a style="color:red; text-decoration:none;" href="https://hu.wikipedia.org/wiki/Matematika">Forrás: Wikipédia</a></p>

<?php include ('footer.php') ?>